resources:
- manager.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: config
    files:
      - krakend-chart.tgz
generatorOptions:
  disableNameSuffixHash: true

images:
  - name: controller
    newName: ghcr.io/nais/krakend-operator
    newTag: main