resources:
- manager.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- files:
  - krakend-chart.tgz
  name: config
generatorOptions:
  disableNameSuffixHash: true

images:
- name: controller
  newName: europe-north1-docker.pkg.dev/nais-io/nais/images/krakend-operator
  newTag: latest
