---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apiendpoints
  failurePolicy: Fail
  name: apiendpoints.krakend.nais.io
  rules:
  - apiGroups:
    - krakend.nais.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - apiendpoints
  sideEffects: None
