apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: nais
  name: debug
spec:
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: "nav:krakend:demo"
          enabled: true
          product: "demo"
          allowedIntegrations:
            - maskinporten
          atMaxAge: 120
          consumers:
            - name: NAV
              orgno: "889640782"
  image: europe-north1-docker.pkg.dev/nais-io/nais/images/testapp:latest
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi

