apiVersion: krakend.nais.io/v1
kind: ApiEndpoints
metadata:
  name: fss-up
spec:
  appName: fss-up
  auth:
    name: maskinporten
    cache: true
    debug: true
    scope:
      - "nav:plattformsikkerhet:krakend.demo"
  rateLimit:
    maxRate: 10
    clientMaxRate: 0
    strategy: ip
    capacity: 0
    clientCapacity: 0
    every: 20s
  endpoints:
    - path: /fss/up
      method: GET
      forwardHeaders:
        - Authorization
      backendHost: https://aura-gw.dev-fss-pub.nais.io
      backendPath: /up