apiVersion: krakend.nais.io/v1
kind: ApiEndpoints
metadata:
  name: app1
spec:
  krakend: namespace1
  appName: app1
  auth:
    name: maskinporten
    cache: true
    debug: true
    audience:
      - "audience1"
    scope:
      - "scope1"
  rateLimit:
    maxRate: 10
    clientMaxRate: 0
    strategy: ip
    capacity: 0
    clientCapacity: 0
    every: 20s
  endpoints:
    - path: /app1/somepath
      method: GET
      timeout: 2s
      forwardHeaders:
        - Authorization
      queryParams:
        - foo
        - bar
      backendHost: http://app1
      backendPath: /api/somepath
  openEndpoints:
    - path: /app1/doc
      method: GET
      backendHost: http://app1
      backendPath: /doc
