apiVersion: krakend.nais.io/v1
kind: Krakend
metadata:
  name: team1
spec:
  name: team1
  ingressHost: team1.nais.io
  authProviders:
    - name: maskinporten
      alg: RS256
      jwkUrl: "https://mock-oauth2-server.dev.dev-nais.cloud.nais.io/debugger/jwks"
      issuer: "https://mock-oauth2-server.dev.dev-nais.cloud.nais.io/debugger"
