apiVersion: krakend.nais.io/v1
kind: ApiEndpoints
metadata:
  labels:
    app.kubernetes.io/name: apiendpoints
    app.kubernetes.io/instance: apiendpoints-sample
    app.kubernetes.io/part-of: krakend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: krakend
  name: apiendpoints-sample
spec:
  krakendInstance: team1-min
  appName: app1
  auth:
    name: maskinporten
    cache: true
    debug: true
    audience:
      - "yolo"
    scope:
      - "scope1"
  # TODO: api doc and swagger?
  endpoints:
    - path: /api1/somepath2
      method: GET
      backendHost: example2.com
      backendPath: /api1/somepath
      forwardHeaders:
        - X-Forwarded-For
      queryParams:
        - foo
        - bar
      rateLimit:
        maxRate: 10
        clientMaxRate: 0
        strategy: ip
        capacity: 0
        clientCapacity: 0
  openEndpoints:
    - path: /api1/doc
      method: GET
      backendHost: example2.com
      backendPath: /api1/doc
