apiVersion: krakend.nais.io/v1
kind: ApiEndpoints
metadata:
  name: apiendpoints-sample
spec:
  krakendInstance: team1-min
  appName: app1
  auth:
    name: maskinporten
    cache: true
    debug: true
    audience:
      - "yolo"
    scope:
      - "scope1"
  endpoints:
    - path: /api1/somepath2
      method: GET
      backendHost: example2.com
      backendPath: /api1/somepath
      forwardHeaders:
        - X-Forwarded-For
      queryParams:
        - foo
        - bar
      rateLimit:
        maxRate: 10
        clientMaxRate: 0
        strategy: ip
        capacity: 0
        clientCapacity: 0
  openEndpoints:
    - path: /api1/doc
      method: GET
      backendHost: example2.com
      backendPath: /api1/doc
