apiVersion: krakend.nais.io/v1
kind: Krakend
metadata:
  name: team1
spec:
  name: team1
  ingress:
    enabled: true
    className: "nais-ingress"
    annotations: {}
    hosts:
      - host: team1.nais.io
        paths:
          - path: /
            pathType: ImplementationSpecific
  authProviders:
    - name: maskinporten
      alg: RS256
      jwkUrl: "https://mock-oauth2-server.dev.dev-nais.cloud.nais.io/debugger/jwks"
      issuer: "https://mock-oauth2-server.dev.dev-nais.cloud.nais.io/debugger"
  deployment:
    replicaCount: 2
    image:
      registry: docker.io
      repository: devopsfaith/krakend
      tag: "2.4.3"
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    extraEnvVars:
      - name: MY_ENV_VAR
        value: "my-value"
