apiVersion: krakend.nais.io/v1
kind: Krakend
metadata:
  labels:
    app.kubernetes.io/name: krakend
    app.kubernetes.io/instance: krakend-sample
    app.kubernetes.io/part-of: krakend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: krakend
  name: team1
spec:
  name: team1
  ingress:
    # set defaults if not set
    enabled: true
    className: "nais-ingress"
    annotations: {}
    hosts:
      - host: team1.nais.io
        paths:
          - path: /
            pathType: ImplementationSpecific
  deployment:
    replicaCount: 2
    image:
      tag: 2.4.3
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi


