apiVersion: krakend.nais.io/v1
kind: ApiEndpoints
metadata:
  name: app1-endpoints
spec:
  krakendInstance: apigw1
  apiName: app1
  auth:
    alg: "RS256"
    cache: true
    debug: true
    jwkUrl: "https://mock-oauth2-server.dev.dev-nais.cloud.nais.io/debugger/jwks"
    issuer: "https://mock-oauth2-server.dev.dev-nais.cloud.nais.io/debugger"
    audience:
      - "yolo"
  # scope:
  #   - "scope1"
  # TODO: api doc and swagger?
  endpoints:
    - path: /echo
      method: GET
      backendHost: http://echo:1027
      backendPath: /
    - path: /echo2
      method: GET
      backendHost: http://echo:1027
      backendPath: /
