apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "krakend-operator.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: krakend
    app.kubernetes.io/part-of: krakend
  {{- include "krakend-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}