krakend:
  #krakend:
  replicaCount: 2
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
  ingress:
    enabled: true
    className: "nais-ingress-external"
    annotations: {}