# -- (int) Number of replicas to deploy
krakend:
  krakend:
    partials:
      endpoints.tmpl: |-
        [
          {
            "endpoint": "/echo",
            "method": "GET",
            "output_encoding": "no-op",
            "extra_config": {
              "auth/validator": {
                "operation_debug": true,
                "alg": "RS256",
                "jwk_url": "https://mock-oauth2-server.dev.dev-nais.cloud.nais.io/debugger/jwks",
                "issuer": "https://mock-oauth2-server.dev.dev-nais.cloud.nais.io/debugger",
                "audience": [
                  "yolo"
                ]
              },
              "qos/ratelimit/router": {
                "max_rate": 1,
                "client_max_rate": 0,
                "strategy": "ip",
                "capacity": 0,
                "client_capacity": 0
              }
            },
            "backend": [
                {
                    "method": "GET",
                    "host": [
                      "http://echo"
                    ],
                    "url_pattern": "/",
                    "encoding": "no-op"
                }
            ]
          },
          {
            "endpoint": "/test",
            "method": "GET",
            "backend": [
                {
                    "method": "GET",
                    "host": [],
                    "url_pattern": "/__debug/roots",
                    "encoding": "json",
                    "deny": [
                        "message"
                    ]
                }
            ],
            "extra_config": {
                "proxy": {
                    "static": {
                        "data": {
                            "collection": [
                                {
                                    "directories": [
                                        "Gracelands"
                                    ]
                                }
                            ],
                            "version": "deficient"
                        },
                        "strategy": "always"
                    }
                }
            },
            "output_encoding": "json"
          }
        ]

  replicaCount: 1

  # -- (object) The securityContext to use for the krakend pod
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  # fsGroup: 2000

  # -- (object) The securityContext to use for the krakend container
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
  ingress:
    # -- (bool) Specifies whether an ingress should be created
    enabled: true
    # -- (string) The class to use for the ingress
    className: "nais-ingress"
    # -- (object) The annotations to use for the ingress
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # -- (list) The list of hosts to use for the ingress
    hosts:
      - host: krakend.dev.dev-nais.cloud.nais.io
        paths:
          - path: /
            pathType: ImplementationSpecific
